install:
		pip install --upgrade pip && \
		pip install -r requirements.txt
		
install-gcp:
		pip install --upgrade pip && \
		pip install -r requirements-gcp.txt

install-aws:
		pip install --upgrade pip && \
		pip install -r requirements-aws.txt

lint:
		pylint --disable=R,C source.py 

format:
		black *.py 

test:
		python -m pytest -vv --cov=source test_source.py 