name: GCP Python 3.10
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix: 
        python-version: [3.8,3.9,3.10.10] 

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with: 
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        make -f MakeFile install-gcp
    - name: Lint
      run: |
        make -f MakeFile lint
    - name: Test
      run: |
        make -f MakeFile test
    - name: Format
      run: |
        make -f MakeFile  format